language: r
cache: packages
sudo: false
pandoc: false

r_binary_packages:
  - devtools
  - roxygen2
  - tidyverse
  - tidyr
  - dplyr
  - futile.logger
  - lubridate
  - openxlsx
  - reshape2
  - ggplot2
  - sqldf
  - formatR
  - stringr

r_packages:
  - bupaR
  - heuristicsmineR
  - petrinetR


r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

before_install:
  - "export DISPLAY=:99.0"
  - cd DataDiggersPackage

after_success:
  - Rscript -e 'devtools::install();devtools::test()'
